# Generated by Django 4.1.1 on 2022-09-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
